# -*- coding: utf-8 -*-
"""config.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awniAIo17h9xO-6zMMpWOHBGYW3HKImE
"""

DEFECT_CATEGORIES = [
    "off_by_one", "incorrect_operator", "missing_condition", "wrong_variable",
    "incorrect_loop", "missing_statement", "wrong_order", "incorrect_comparison",
    "missing_initialization", "wrong_data_structure", "incorrect_return",
    "missing_edge_case", "wrong_algorithm", "other"
]

QUIXBUGS_PROGRAMS = [
    "breadth_first_search", "depth_first_search", "detect_cycle",
    "find_first_in_sorted", "find_in_sorted", "gcd", "get_factors",
    "hanoi", "is_valid_parenthesization", "kheapsort", "knapsack",
    "kth", "levenshtein", "lis", "longest_common_subsequence", "lcs_lenghth",
    "max_sublist_sum", "mergesort", "next_palindrome", "next_permutation",
    "pascal", "possible_change", "powerset", "quicksort", "reverse_linked_list",
    "rpn_eval", "shortest_path_length", "shortest_path_lengths", "sieve",
    "sqrt", "subsequences", "to_base",
    "topological_ordering", "wrap", "bitcount", "bucketsort", "flatten",
    "shunting_yard", "node"
]
