# -*- coding: utf-8 -*-
"""fetchers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZGpldKOF0cLfHAZg-9cSuYFrCdAzJsw
"""

import requests
import json
from langchain.tools import tool

@tool
def fetch_buggy_code(program_name: str) -> Dict[str, Any]:
    """Fetch buggy code and test cases from the QuixBugs repository"""
    base_url = "https://raw.githubusercontent.com/RumbleJack56/Code-Refactoring-QuixBugs/master"

    try:
        code_url = f"{base_url}/python_programs/{program_name}.py"
        code_response = requests.get(code_url)

        if code_response.status_code != 200:
            return {"error": f"Could not fetch code for {program_name}", "success": False}

        buggy_code = code_response.text

        test_url = f"{base_url}/json_testcases/{program_name}.json"
        test_response = requests.get(test_url)

        test_cases = []
        if test_response.status_code == 200:
            test_lines = test_response.text.strip().splitlines()
            test_cases = [json.loads(line) for line in test_lines if line.strip()]


        return {
            "buggy_code": buggy_code,
            "test_cases": test_cases,
            "success": True
        }

    except Exception as e:
        return {"error": str(e), "success": False}

print(" GitHub data fetcher tools defined")