# -*- coding: utf-8 -*-
"""save.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCca23IxzjZn2Ovbd9IC8XifjVaNvjXy
"""

import os

def save_fixed_code(program_name, fixed_code):
    os.makedirs('fixed_programs', exist_ok=True)

    code = fixed_code.strip()
    if code.startswith("```"):
        code = code.split('```')[1]
        if code.startswith('python'):
            code = code[len('python'):].lstrip('\n')

    file_path = os.path.join('fixed_programs', f'{program_name}.py')
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(code)
    print(f"Saved fixed code to: {file_path}")