# -*- coding: utf-8 -*-
"""workflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1azT8Ze2hZDecbh5vuRaEe1np3S5NT-L1
"""

from langgraph.graph import StateGraph, START, END
from agents import agent1_fetch_and_categorize, agent2_understand_code, agent3_fix_code, AgentState

def create_code_correction_workflow():
    """Create the multi-agent workflow using LangGraph"""

    workflow = StateGraph(AgentState)

    workflow.add_node("fetch_categorize", agent1_fetch_and_categorize)
    workflow.add_node("understand_code", agent2_understand_code)
    workflow.add_node("fix_code", agent3_fix_code)

    workflow.add_edge(START, "fetch_categorize")
    workflow.add_edge("fetch_categorize", "understand_code")
    workflow.add_edge("understand_code", "fix_code")
    workflow.add_edge("fix_code", END)

    return workflow.compile()

code_correction_graph = create_code_correction_workflow()
print("Multi-agent workflow created successfully")